In [37]:
import numpy as np
import pandas as pd
import sys
import time

Comparing NumPy arrays and Python size

In [23]:
l = range(1000)
x = sys.getsizeof(1000)*len(l)

type(x)
print(x)

# for i in range(10):
#     print(l[i], end=' ')

28000


In [6]:
array = np.arange(1000)
print(array.size*array.itemsize)

8000


Processing time

In [34]:
SIZE = 10

l1 = range(SIZE)
l2 = range(SIZE)


In [36]:
a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

In [50]:
begin = time.time()

In [51]:
result = [(x+y) for x, y in zip(l1, l2)]


print("python list processing: ", (time.time() - begin)*10)

python list processing:  10.0968599319458


In [46]:
begin = time.time()

result = a1+a2

print("numpy list processing: ", (time.time() - begin)*10)

numpy list processing:  0.0008130073547363281


In [52]:
print(a1+a2)

[ 0  2  4  6  8 10 12 14 16 18]


In [53]:
print(a1-a2)

[0 0 0 0 0 0 0 0 0 0]


In [54]:
print(a1*a2)

[ 0  1  4  9 16 25 36 49 64 81]


## NumPy Array Object 

In [55]:
# One-dimensional

arr = np.array([5,6,7])
print(arr)

[5 6 7]
